FROM python:3.13.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

ENV PATH="/code/.venv/bin:$PATH"
WORKDIR /code

COPY "pyproject.toml" "uv.lock" ".python-version" ./
RUN uv sync --locked

COPY pipeline_v2.bin .
COPY "q6_predict.py" ./

EXPOSE 4444

ENTRYPOINT ["uvicorn", "q6_predict:lead_scoring", "--host", "0.0.0.0", "--port", "4444"]