FROM agrigorev/zoomcamp-model:2025

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /code

ENV PATH="/code/.venv/bin:$PATH"

COPY "pyproject.toml" "uv.lock" ".python-version" ./
RUN uv sync --locked

COPY "main.py" ./

EXPOSE 4444

ENTRYPOINT ["uvicorn", "main:predict_churn_telco", "--host", "0.0.0.0", "--port", "4444"]